### ISSUE TITLE
Can't compile your include

### ISSUE THREAD

**Issue by Tenk4** [TheManyula/progress3D#1]
I just notice progress3D only
I didn't put any code yet then I can't compile
Below's my all include in used

#include 		<a_samp>
#include 		<a_mysql>
#include		<easyDialog>
#include		<sscanf2>
#include		<zcmd>
#include		<foreach>
#include		<progress3D>
#include		<crashdetect>

Here's the error lines

`F:\SAMP\pawno\include\progress3D.inc(36) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(65) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(65) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(66) : error 001: expected token: ";", but found "-identifier-"
F:\SAMP\pawno\include\progress3D.inc(68) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(69) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(71) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(74) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(74) : error 025: function heading differs from prototype
F:\SAMP\pawno\include\progress3D.inc(74) : error 021: symbol already defined: "UpdateProgress"
F:\SAMP\pawno\include\progress3D.inc(76) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(82) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(83) : error 010: invalid function or declaration
F:\SAMP\pawno\include\progress3D.inc(86) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(101) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(108) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(117) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(124) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(133) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(140) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(149) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(156) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(165) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(172) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\pawno\include\progress3D.inc(181) : warning 219: local variable "barid" shadows a variable at a preceding level
F:\SAMP\gamemodes\new.pwn(74) : symbol is never used: "UpdateProgress"
F:\SAMP\pawno\include\progress3D.inc(66) : symbol is never used: "barid"
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2016, ITB CompuPhase

11 Errors.`

**Comment by Tenk4** [comment]
Solved now
I just take lower version of streamer and Its all work perfectly
This all error just happens to streamer 2.9.4 the lastest version

**Comment by TheManyula** [comment]
I've looked into that. These errors are caused by streamer version 2.9.4, no idea why. This streamer version seems to have a bunch of issues, so just stick to v2.9.3 for now.

**Comment by TheManyula** [comment]
I didn't take a close enough look the first time. The issue was that the areaid parameter now doesn't use a streamer-custom tag anymore. I removed it from the CreateProgressBar3D definition. Version 2.0 of progress3D is now compatible with streamer version 2.9.4.
